server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_system
    schema: ?payment_system_storage
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob.non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate